In [36]:
import sys

!{sys.executable} -m pip install python-dotenv

Requirement already satisfied: python-dotenv in /Users/cherguiadem/.pyenv/versions/3.13.13/envs/rec_o/lib/python3.13/site-packages (1.2.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [37]:
from dotenv import load_dotenv

print("dotenv OK")

dotenv OK

In [38]:
import os
import psycopg2
from dotenv import load_dotenv

load_dotenv("../.env")

conn = psycopg2.connect(
    host=os.getenv("POSTGRES"),
    port=5432,
    database=os.getenv("DATABASE"),
    user=os.getenv("DB_USERNAME"),
    password=os.getenv("DB_PASSWORD")
)

print("Connexion OK")

Connexion OK

In [39]:
import pandas as pd

query = """
SELECT
    a.name AS artist_name,
    rg.name AS album_name
FROM musicbrainz.l_artist_release_group l
JOIN musicbrainz.artist a
    ON l.entity0 = a.id
JOIN musicbrainz.release_group rg
    ON l.entity1 = rg.id
LIMIT 20;
"""

df = pd.read_sql(query, conn)

df

/var/folders/yn/fvh46w1d6tv6lxys_3t_l2rr0000gn/T/ipykernel_17740/2449627440.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

            artist_name                                         album_name
0         Sopa de Cabra    Podré tornar enrere. El tribut a Sopa de Cabra.
1        John Malm, Jr.                                   Head Like a Hole
2         Päkkos Gustaf  Bingsjö by Anders Bjernulf, a tribute to Päkko...
3        John Malm, Jr.                                         Down in It
4   Ben “Lambo” Lambert                                            Alfredo
5             Andy Siry                                   Serenity in Fire
6       Nine Inch Nails  Special Tribute to Nine Inch Nails: Soundtrack...
7      Michelle Pearson                                 Who We Are Instead
8    Kris Kristofferson                               Nothing Left to Lose
9       Søren Hedegaard                           Under stjernerne et sted
10        Pernille Holm                           Under stjernerne et sted
11       John Malm, Jr.                        The Day the World Went Away
12      Stefano Bollani                               Abbassa la tua radio
13                  091               Partiendo de cero: El homenaje a 091
14                  091       Canciones de cuna y de rabia: Homenaje a 091
15               Alaska                                  Homenaje a Alaska
16           Pink Floyd  Jazzitaliano Live 2008: Us and Them: Omaggio a...
17          Iron Maiden  The Golden Beast: A Tribute From Colombia to I...
18    Amorine Dallançon                       Echoes From Forgotten Hearts
19    Jorge Luis Borges  Borges: Homenaje en el centenario de su natalicio

In [40]:
print(conn.closed)

0

In [41]:
import pandas as pd

query = """
SELECT
    a.name AS artist_name,
    rg.name AS album_name
FROM musicbrainz.l_artist_release_group l
JOIN musicbrainz.artist a
    ON l.entity0 = a.id
JOIN musicbrainz.release_group rg
    ON l.entity1 = rg.id
LIMIT 20;
"""

df = pd.read_sql(query, conn)

df

/var/folders/yn/fvh46w1d6tv6lxys_3t_l2rr0000gn/T/ipykernel_17740/2449627440.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

            artist_name                                         album_name
0         Sopa de Cabra    Podré tornar enrere. El tribut a Sopa de Cabra.
1        John Malm, Jr.                                   Head Like a Hole
2         Päkkos Gustaf  Bingsjö by Anders Bjernulf, a tribute to Päkko...
3        John Malm, Jr.                                         Down in It
4   Ben “Lambo” Lambert                                            Alfredo
5             Andy Siry                                   Serenity in Fire
6       Nine Inch Nails  Special Tribute to Nine Inch Nails: Soundtrack...
7      Michelle Pearson                                 Who We Are Instead
8    Kris Kristofferson                               Nothing Left to Lose
9       Søren Hedegaard                           Under stjernerne et sted
10        Pernille Holm                           Under stjernerne et sted
11       John Malm, Jr.                        The Day the World Went Away
12      Stefano Bollani                               Abbassa la tua radio
13                  091               Partiendo de cero: El homenaje a 091
14                  091       Canciones de cuna y de rabia: Homenaje a 091
15               Alaska                                  Homenaje a Alaska
16           Pink Floyd  Jazzitaliano Live 2008: Us and Them: Omaggio a...
17          Iron Maiden  The Golden Beast: A Tribute From Colombia to I...
18    Amorine Dallançon                       Echoes From Forgotten Hearts
19    Jorge Luis Borges  Borges: Homenaje en el centenario de su natalicio